logging: "aim"
log_repo: "logs/aim/.aim"
seed: 1
env_params:
  env_name: "brax-halfcheetah"
  max_ep_length: 1000
  init_kwargs:
    backend: "spring"
num_timesteps: 50000000
ppo_overrides:
  num_evals: 20
  reward_scaling: 1
  action_repeat: 1
  normalize_observations: true
  unroll_length: 20
  num_minibatches: 32
  num_updates_per_batch: 8
  discounting: 0.95
  learning_rate: 0.0003
  entropy_cost: 0.001
  num_envs: 2048
  batch_size: 512
