logging: "aim"
log_repo: "logs/aim/.aim"
env_params:
  env_name: "brax-hopper"
  init_kwargs:
    backend: "spring"
num_timesteps: 5000000
ppo_overrides:
  discounting: 0.99
  num_evals: 25
  batch_size: 8
  normalize_observations: true
  reward_scaling: 12.5
  unroll_length: 20
  gae_lambda: 0.97
