logging: "aim"
log_repo: "logs/aim/.aim"
env_params:
  env_name: "brax-hopper"
  init_kwargs:
    backend: "spring"
num_timesteps: 5000000
ppo_overrides:
  discounting: 0.99
  num_evals: 25
  batch_size: 32
  normalize_observations: true
  reward_scaling: 10
  entropy_cost: 0.001
  unroll_length: 30
