logging: aim
episodes: 50000
patience: 20
env_params:
  env_name: "brax-hopper"
  batch_size: 1
  obs_mask: [0, 2, 4, 6, 8, 10]
  init_kwargs:
    backend: "spring"
trace_mode: "accumulate"
gamma: 0.99
lambda_v: 0.9
lambda_pi: 0.9
lambda_rnn: 0.9
eta_f: 0
entropy_rate: 1e-5
steps: 1000
eval_every: 100
pass_obs: false
optimizer_params_td:
  learning_rate: "1e-4"
optimizer_params_rnn:
  learning_rate: "1e-4"
  gradient_clip: 1.0
