logging: "aim"
log_repo: "logs/aim/.aim"
seed: 1
env_params:
  env_name: "brax-hopper"
  obs_mask: [0, 2, 4, 6, 8, 10]
  max_ep_length: 1000
  init_kwargs:
    backend: "spring"
num_timesteps: 6553600
sac_overrides:
  num_evals: 20
  reward_scaling: 30
  action_repeat: 1
  normalize_observations: true
  discounting: 0.997
  learning_rate: 0.0006
  num_envs: 128
  batch_size: 512
  grad_updates_per_step: 64
  max_devices_per_host: 1
  max_replay_size: 1048576
  min_replay_size: 8192
